apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-clamify-api
  labels:
    app: dev-clamify-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-clamify-api
  template:
    metadata:
      labels:
        app: dev-clamify-api
    spec:
      containers:
      - env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: DB_CONNECTION_STRING
              name: dev-clamify-secret
        name: dev-clamify-api
        image: ghcr.io/cdconn00/clamify-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
