name: build and test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  DOTNET_VERSION: '6.0.302' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
    
    - name: Run Unit and Integration Tests
      run: dotnet test Clamify.sln
   
  docker-build:
      name: build-and-test-${{matrix.os}}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]

      steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag ${GITHUB_RUN_ID} --file Dockerfile .
